## Compulsary Task1

Hemant Thapa

### Importing Libraries

In [1]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
from sklearn import preprocessing
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

### Importing DataSet

In [2]:
df = pd.read_csv('Iris.csv')
# Reading first 10 top files
df.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

### Checking Row and Columns

In [3]:
df.shape

(150, 6)

converting the 'Species' column in the df pandas dataframe from its current data type to a categorical data type. 

In [4]:
df['Species'] = df['Species'].astype('category')

creating a new column SpeciesType in the df pandas dataframe and assigning to it the integer codes that represent the categories of the 'Species' column.

In [5]:
df['SpeciesType'] = df['Species'].cat.codes

### Checking Unique Values 

In [6]:
df['Species'].unique()

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Categories (3, object): ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [7]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  SpeciesType  
145  Iris-virginica            2  
146  Iris-virginica            2  
147  Iris-virginica            2  
148  Iris-virginica            2  
149  Iris-virginica            2

### Checking Unique Values in SpeciesType

In [8]:
df.SpeciesType.unique()

array([0, 1, 2], dtype=int8)

In [9]:
df.Species.unique()

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Categories (3, object): ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

### Replacing Value 

In [10]:
df['SpeciesType'] = df['SpeciesType'].replace(2, 1)

In [11]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  SpeciesType  
145  Iris-virginica            1  
146  Iris-virginica            1  
147  Iris-virginica            1  
148  Iris-virginica            1  
149  Iris-virginica            1

In [12]:
df.shape

(150, 7)

In [13]:
df.SpeciesType.unique()

array([0, 1], dtype=int8)

### Creating Independent X and Dependent Y variables

In [14]:
#Declaring X
x = df.iloc[:,[1,2,3,4]]
x[:5]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [15]:
#Declaring Y
y = df.SpeciesType
y.tail(5)

145    1
146    1
147    1
148    1
149    1
Name: SpeciesType, dtype: int8

### Training and Test DataSet

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, shuffle = True)

### Checking Shape of DataSet after spliting into Training and Test Dataset

In [17]:
print("Training Data: ", x_train.shape, y_train.shape)
print("Test Data: ", x_test.shape, y_test.shape)

Training Data:  (120, 4) (120,)
Test Data:  (30, 4) (30,)


### Biases or Anomalies

#### Check for any imbalances or deviations in the split, such as if y_test contains a disproportionate number of instances of one value.

In [18]:
print(f"y_train :{y_train}")

y_train :69     1
12     0
86     1
138    1
143    1
      ..
107    1
47     0
120    1
99     1
102    1
Name: SpeciesType, Length: 120, dtype: int8


In [19]:
print(f"y_test  :{y_test}")

y_test  :13     0
125    1
2      0
25     0
42     0
30     0
72     1
31     0
111    1
110    1
29     0
130    1
113    1
55     1
61     1
139    1
73     1
38     0
119    1
53     1
34     0
78     1
17     0
131    1
8      0
79     1
93     1
140    1
115    1
40     0
Name: SpeciesType, dtype: int8


### Creating Logistice Regression Model

In [20]:
logistic_regression = LogisticRegression()
model = logistic_regression.fit(x_train, y_train)

### Predicting Value

In [21]:
y_pred = model.predict(x_test)

In [22]:
y_pred[0:5]

array([0, 1, 0, 0, 0], dtype=int8)

### Confusion Matrix

In [23]:
conf_matrix = confusion_matrix(y_test, y_pred)

In [24]:
print(conf_matrix)

[[12  0]
 [ 0 18]]


In [25]:
print(f'Accuracy of logistic regression in predicting iris setosa species: {logistic_regression.score(x_test, y_test)}')

Accuracy of logistic regression in predicting iris setosa species: 1.0


In [26]:
def precision(TP, FP):
    return (TP/ (TP + FP))

def recall (TP, FN):
    return (TP/ (TP + FN))

TP = conf_matrix[0][0]
FP = conf_matrix[0][1]
FN = conf_matrix[1][0]
TN = conf_matrix[1][1]

print(f"TP: {TP}, FP: {FP}, FN: {FN}, TN: {TN}")

TP: 12, FP: 0, FN: 0, TN: 18


#### Based on the confusion matrix, it appears that both precision and recall will have a value of 1.0. Precision is a measure of how many of the positive predictions were actually correct, and recall is a measure of how many of the actual positive cases were correctly predicted. In this case, with 0 false positives and 0 false negatives, both precision and recall will have a value of 1.0, indicating a perfect score.



In [27]:
print(f"The precision of model: {precision(TP, FP)}.")
print(f"The recall this model: {recall(TP, FN)}.")

The precision of model: 1.0.
The recall this model: 1.0.
